name: "Pull Request Labeler"
on:
- pull_request

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: gerrymanoim/pr-prefix-labeler
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
